spring:
  application:
    name: ai
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
      chat:
        options:
          model: qwen-plus
#    ollama:
#          base-url: http://localhost:11434
#          chat:
#            model: deepseek-r1:1.5b
    mcp:
      client:
        stdio:
          servers-configuration: classpath:mcp.json
server:
  port: 8123
  servlet:
    context-path: /api

# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.chen.aiagent.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
